### ISSUE TITLE
Bluloco Dark PyCharm

### ISSUE THREAD

**Issue by JohannesJungbluth** [uloco/webstorm-bluloco-scheme#2]
In Bluloco Dark, Night, Dim and Material with PyCharm are serveral types black and not really readable:

- Decorater (dark blue)
- Class definition (black)
- Function definition (black)
- Keyword argument (dark purple)
- Buil-in name (dark blue)

![2017-04-06 12_39_11-test - c__users_topuzoglu u_pycharmprojects_test - _test py - pycharm commu](https://cloud.githubusercontent.com/assets/4216502/24750893/d4d9dcf4-1ac7-11e7-8aa5-a9dc9207a194.png)

**Comment by uloco** [comment]
fixed in f7b6bfe29eb443ac8ac6a12dc6b8f22339b79dc5
