### ISSUE TITLE
Update webstorm-bluloco-scheme  for webstorm pls

### ISSUE THREAD

**Issue by Antoshkiv** [uloco/webstorm-bluloco-scheme#4]

**Comment by uloco** [comment]
Is there a trial version, because I stopped using it years ago …

**Comment by Antoshkiv** [comment]
https://www.jetbrains.com/webstorm/whatsnew/ first 30 days is free

may i ask u why do u stopped use webstorm?

**Comment by uloco** [comment]
I stopped using it back then, because the VSCode Vim plugin worked better than the Webstorm one.
Now VSCode is finally so advanced and I really like it, that I don't want to turn back.

**Comment by uloco** [comment]
What is not working or, what are you missing?

**Comment by uloco** [comment]
Updated. If anything is off or missing, just ping. :)
